# Generated by Django 4.1.7 on 2023-04-13 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_rename_rant_rant_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="rant",
            name="user",
            field=models.ForeignKey(
                default="",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users_rant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
