# Generated by Django 4.1.7 on 2023-04-13 03:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="rant",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="rant",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
